# Generated by Django 5.0 on 2023-12-22 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('grade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('current_gpa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('target_gpa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gpa_scale', models.DecimalField(decimal_places=2, default=4.0, max_digits=3)),
            ],
        ),
    ]
