# Generated by Django 5.0 on 2023-12-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='credits',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='current_gpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='gpa_scale',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='grade',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='target_gpa',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
