# Generated by Django 5.0 on 2023-12-23 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpaapp', '0002_course_credits_alter_course_current_gpa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_gpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('previous_credits', models.DecimalField(decimal_places=2, max_digits=5)),
                ('number_of_courses', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='current_gpa',
        ),
        migrations.RemoveField(
            model_name='course',
            name='gpa_scale',
        ),
        migrations.RemoveField(
            model_name='course',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='course',
            name='name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='target_gpa',
        ),
        migrations.AddField(
            model_name='course',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gpaapp.semester'),
            preserve_default=False,
        ),
    ]
